// Code generated by counterfeiter. DO NOT EDIT.
package mappingfakes

import (
	"context"
	"sync"

	"github.com/mdevilliers/org-scrounger/pkg/gh"
)

type FakeRepoGetter struct {
	GetRepoByNameStub        func(context.Context, string, string) (gh.RepositorySlim, gh.RateLimit, error)
	getRepoByNameMutex       sync.RWMutex
	getRepoByNameArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}
	getRepoByNameReturns struct {
		result1 gh.RepositorySlim
		result2 gh.RateLimit
		result3 error
	}
	getRepoByNameReturnsOnCall map[int]struct {
		result1 gh.RepositorySlim
		result2 gh.RateLimit
		result3 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeRepoGetter) GetRepoByName(arg1 context.Context, arg2 string, arg3 string) (gh.RepositorySlim, gh.RateLimit, error) {
	fake.getRepoByNameMutex.Lock()
	ret, specificReturn := fake.getRepoByNameReturnsOnCall[len(fake.getRepoByNameArgsForCall)]
	fake.getRepoByNameArgsForCall = append(fake.getRepoByNameArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.GetRepoByNameStub
	fakeReturns := fake.getRepoByNameReturns
	fake.recordInvocation("GetRepoByName", []interface{}{arg1, arg2, arg3})
	fake.getRepoByNameMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *FakeRepoGetter) GetRepoByNameCallCount() int {
	fake.getRepoByNameMutex.RLock()
	defer fake.getRepoByNameMutex.RUnlock()
	return len(fake.getRepoByNameArgsForCall)
}

func (fake *FakeRepoGetter) GetRepoByNameCalls(stub func(context.Context, string, string) (gh.RepositorySlim, gh.RateLimit, error)) {
	fake.getRepoByNameMutex.Lock()
	defer fake.getRepoByNameMutex.Unlock()
	fake.GetRepoByNameStub = stub
}

func (fake *FakeRepoGetter) GetRepoByNameArgsForCall(i int) (context.Context, string, string) {
	fake.getRepoByNameMutex.RLock()
	defer fake.getRepoByNameMutex.RUnlock()
	argsForCall := fake.getRepoByNameArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeRepoGetter) GetRepoByNameReturns(result1 gh.RepositorySlim, result2 gh.RateLimit, result3 error) {
	fake.getRepoByNameMutex.Lock()
	defer fake.getRepoByNameMutex.Unlock()
	fake.GetRepoByNameStub = nil
	fake.getRepoByNameReturns = struct {
		result1 gh.RepositorySlim
		result2 gh.RateLimit
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeRepoGetter) GetRepoByNameReturnsOnCall(i int, result1 gh.RepositorySlim, result2 gh.RateLimit, result3 error) {
	fake.getRepoByNameMutex.Lock()
	defer fake.getRepoByNameMutex.Unlock()
	fake.GetRepoByNameStub = nil
	if fake.getRepoByNameReturnsOnCall == nil {
		fake.getRepoByNameReturnsOnCall = make(map[int]struct {
			result1 gh.RepositorySlim
			result2 gh.RateLimit
			result3 error
		})
	}
	fake.getRepoByNameReturnsOnCall[i] = struct {
		result1 gh.RepositorySlim
		result2 gh.RateLimit
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeRepoGetter) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getRepoByNameMutex.RLock()
	defer fake.getRepoByNameMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeRepoGetter) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
