name: ci

on:
  push:
    branches: main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: setup
      uses: actions/setup-go@v4
      with:
        go-version: '1.19'
    - name: build
      run: make build 
      
    - name: lint
      run: make lint
    
    # Run testing on the code
    - name: test
      run: make test
